mod_tool_version = "4.9.0-beta2"
type = "export_bundled"

[mods.licence.license_name]
"RELEASE YEAR" = "1976"
"NAME EN" = "license name"
"LICENCE TYP" = "BOARD"
"BAD GENRE" = "Economic Simulation"
requires_pictures = false
"GOOD GENRE" = "Fighting Game"

[mods.dev_legend.devlegendname]
TYP = "D"
"NAME EN" = "devlegendname"
requires_pictures = false
WOMAN = "false"

[mods.anti_cheat.anticheatname]
DATE = "JAN 1976"
"NAME EN" = "anticheatname"
PRICE = "30000"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.npc_game.npcgamename]
requires_pictures = false
GENRES = "<Building Game>"
"NAME EN" = "npcgamename"

[mods.hardware_feature.hardwarefeaturename]
DATE = "JAN 1976"
"NAME EN" = "hardwarefeaturename"
"RES POINTS" = "500"
QUALITY = "2"
PRICE = "30000"
ONLY_STATIONARY = ""
requires_pictures = false
"DEV COSTS" = "35000"
"DESC EN" = "hardwarefeaturedescription"

[mods.npc_ip.npcipname]
"NAME EN" = "npcipname"
sub_theme = "Angels"
sub_genre = "Sports Game"
genre = "Adventure"
release_year = "1976"
rating = "50"
publisher = "Mintendu"
theme = "Angels"
target_group = "ALL"
requires_pictures = false

[mods.engine_feature.enginefeaturename]
"RES POINTS" = "500"
PRICE = "50000"
GRAPHIC = "100"
TYP = "0"
"DESC EN" = "enginefeaturedescription"
DATE = "JAN 1976"
TECH = "100"
"NAME EN" = "enginefeaturename"
GAMEPLAY = "100"
SOUND = "100"
requires_pictures = false
"DEV COSTS" = "35000"
TECHLEVEL = "1"

[mods.platform.platformname]
STARTPLATFORM = ""
COMPLEX = "0"
PRICE = "50000"
INTERNET = "1"
TYP = "0"
DATE = "JAN 1976"
"PIC-2 YEAR" = "1977"
"NAME EN" = "platformname"
platform_image_1 = "platform_platformname_platform_image_1.png"
platform_image_2 = "platform_platformname_platform_image_2.png"
"MANUFACTURER EN" = "platformdescription"
"MANUFACTURER MANUFACTURER EN" = "platformdescription"
NEED-1 = "Arcade Joystick Support"
GAMEPASS = "10"
requires_pictures = true
"DEV COSTS" = "35000"
TECHLEVEL = "1"
UNITS = "1000000"
"DATE END" = "JAN 2034"

[mods.genre.genrename]
"RES POINTS" = "0"
"GAMEPLAYFEATURE BAD" = "<Instrument Support><In-App Purchases><Gaming Vest Support>"
GRAPHIC = "25"
"screenshot_genre_genrename_1.png" = "genre_genrename_screenshot_genre_genrename_1.png"
"DESC EN" = "genredescription"
"screenshot_genre_genrename_2.png" = "genre_genrename_screenshot_genre_genrename_2.png"
FOCUS4 = "5"
ALIGN1 = "5"
FOCUS5 = "5"
ALIGN2 = "5"
FOCUS6 = "5"
FOCUS7 = "5"
FOCUS0 = "5"
"GENRE COMB" = "<Building Game><Economic Simulation><Fighting Game><First-Person Shooter><Interactive Movie>"
FOCUS1 = "5"
FOCUS2 = "5"
FOCUS3 = "5"
ALIGN0 = "5"
GAMEPLAY = "25"
SOUND = "25"
"DEV COSTS" = "0"
PRICE = "0"
iconName = "genre_genrename_icon.png"
"screenshot_genre_genrename_3.png" = "genre_genrename_screenshot_genre_genrename_3.png"
TGROUP = "<ADULT>"
DATE = "JAN 1976"
"GAMEPLAYFEATURE GOOD" = "<Adjustable HUD><Augmented-Reality-Support><Arcade Joystick Support>"
"THEME COMB" = "<Bicycle><Birds><Billiards><Books>"
"NAME EN" = "genrename"
requires_pictures = true
"screenshot_genre_genrename_0.png" = "genre_genrename_screenshot_genre_genrename_0.png"
CONTROL = "25"

[mods.publisher.publishername]
PUBLISHER = "true"
DEVELOPER = "true"
MARKET = "50"
GENRE = "Racing"
ONLYMOBILE = "true"
SHARE = "5"
SPEED = "3"
DATE = "JAN 1976"
COMVAL = "10000000"
"NAME EN" = "publishername"
NOTFORSALE = "true"
publisher_icon = "publisher_publishername_publisher_icon.png"
COUNTRY = "0"
requires_pictures = true

[mods.theme.themename]
"NAME CZ" = "themename"
"NAME JA" = "themename"
GENRES = "<Adventure><Building Game><Economic Simulation><Fighting Game><First-Person Shooter>"
"NAME PB" = "themename"
"NAME AR" = "themename"
"NAME CT" = "themename"
"NAME FR" = "themename"
"NAME IT" = "themename"
"NAME ES" = "themename"
"NAME HU" = "themename"
"NAME EN" = "themename"
"NAME KO" = "themename"
"NAME RU" = "themename"
"NAME CH" = "themename"
"NAME TU" = "themename"
"NAME PL" = "themename"
requires_pictures = false
"NAME GE" = "themename <2><11><9><10><14><M3>"
"NAME RO" = "themename"
AGE = "3"

[mods.gameplay_feature.gameplayfeaturename]
"RES POINTS" = "500"
PRICE = "50000"
BAD = "<Building Game><Economic Simulation><Fighting Game><First-Person Shooter>"
GRAPHIC = "30"
TYP = "4"
"DESC EN" = "gameplayfeaturedescription"
DATE = "JAN 1976"
TECH = "30"
"NAME EN" = "gameplayfeaturename"
GAMEPLAY = "30"
SOUND = "30"
GOOD = "<Sports Game><Strategy><Survival Game><Third-Person Shooter>"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.npc_engine.npcenginename]
PLATFORM = "Personal Computer"
DATE = "JAN 1976"
"NAME EN" = "npcenginename"
PRICE = "30000"
GENRE = "Adventure"
SHARE = "5"
requires_pictures = false

[mods.copy_protect.copyprotectionname]
DATE = "JAN 1976"
"NAME EN" = "copyprotectionname"
PRICE = "30000"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.hardware.hardwarename]
DATE = "JAN 1976"
ONLY_HANDHELD = ""
"NAME EN" = "hardwarename"
"RES POINTS" = "500"
PRICE = "500000"
platform_icon = "hardware_hardwarename_platform_icon.png"
TYP = "0"
requires_pictures = true
"DEV COSTS" = "1000000"
TECHLEVEL = "1"
