mod_tool_version = "4.9.0-dev"
type = "export_bundled"

[mods.licence.licencename]
"RELEASE YEAR" = "1976"
"NAME EN" = "LicenceName"
"LICENCE TYP" = "MOVIE"
"BAD GENRE" = "Adventure"
requires_pictures = false
"GOOD GENRE" = "Strategy"

[mods.dev_legend.levlegendname]
TYP = "D"
"NAME EN" = "LevLegendName"
requires_pictures = false
WOMAN = "false"

[mods.anti_cheat.anticheatname]
DATE = "JAN 1976"
"NAME EN" = "AntiCheatName"
PRICE = "30000"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.npc_game.npcgame]
requires_pictures = false
GENRES = "<GenreName>"
"NAME EN" = "NpcGame"

[mods.hardware_feature.hardwarefeaturename]
DATE = "JAN 1976"
"NAME EN" = "HardwareFeatureName"
"RES POINTS" = "500"
QUALITY = "2"
PRICE = "30000"
NEEDINTERNET = ""
ONLY_STATIONARY = ""
requires_pictures = false
"DEV COSTS" = "35000"
"DESC EN" = "HardwareFeatureDescription"

[mods.npc_ip.npcipname]
"NAME EN" = "NpcIpName"
sub_theme = "Archaeology"
sub_genre = "Interactive Movie"
genre = "Skill Game"
release_year = "1976"
rating = "50"
publisher = "Epix Ware"
theme = "Archaeology"
target_group = "ALL"
requires_pictures = false

[mods.engine_feature.enginefeaturename]
"RES POINTS" = "500"
PRICE = "50000"
GRAPHIC = "100"
TYP = "0"
"DESC EN" = "EngineFeatureDescription"
DATE = "JAN 1976"
TECH = "100"
"NAME EN" = "EngineFeatureName"
GAMEPLAY = "100"
SOUND = "100"
requires_pictures = false
"DEV COSTS" = "35000"
TECHLEVEL = "1"

[mods.platform.platformname]
STARTPLATFORM = ""
COMPLEX = "0"
PRICE = "50000"
INTERNET = "1"
TYP = "1"
DATE = "JAN 1976"
"NAME EN" = "PlatformName"
BACKCOMP-2 = "Mintendu 3SD"
platform_image_1 = "platform_platformname_platform_image_1.png"
BACKCOMP-1 = "Mintendu 3DEX"
"MANUFACTURER EN" = "ManufacturerName"
"MANUFACTURER MANUFACTURER EN" = "ManufacturerName"
NEED-1 = "E-Sport Mode"
GAMEPASS = "10"
PUB = "Mintendu"
requires_pictures = true
"DEV COSTS" = "35000"
TECHLEVEL = "1"
UNITS = "1000000"
BACKCOMP-3 = "Mintendu 63"

[mods.genre.genrename]
"RES POINTS" = "0"
"GAMEPLAYFEATURE BAD" = "<Dynamic & Destructible World><Day-Night Cycle><Dance pad support><Drop in Drop Out Multiplayer>"
"screenshot_1.png" = "genre_genrename_screenshot_1.png"
GRAPHIC = "25"
"DESC EN" = "GenreDescription"
FOCUS4 = "5"
ALIGN1 = "5"
FOCUS5 = "5"
ALIGN2 = "5"
FOCUS6 = "5"
FOCUS7 = "5"
FOCUS0 = "5"
"GENRE COMB" = "<Action><Building Game><Interactive Movie><Platformer><Puzzle Game><Racing><Real-Time Strategy><Role-Playing Game><Simulation><Skill Game><Sports Game><Strategy><Survival Game>"
FOCUS1 = "5"
FOCUS2 = "5"
"screenshot_4.png" = "genre_genrename_screenshot_4.png"
FOCUS3 = "5"
ALIGN0 = "5"
GAMEPLAY = "25"
SOUND = "25"
"screenshot_0.png" = "genre_genrename_screenshot_0.png"
"DEV COSTS" = "0"
PRICE = "0"
iconName = "genre_genrename_icon.png"
"screenshot_3.png" = "genre_genrename_screenshot_3.png"
TGROUP = "<KID><TEEN><ADULT><OLD>"
"screenshot_2.png" = "genre_genrename_screenshot_2.png"
DATE = "JAN 1976"
"GAMEPLAYFEATURE GOOD" = "<Adjustable HUD><Adjustable Censoring><Adjustable Controls>"
"THEME COMB" = "<Pets><Dragons><Hacking><Bicycle><Bounty Hunter><Birds><Pinball><Billiards><Bowling><Drones><Graveyards><Photography><Books><Dolls>"
"NAME EN" = "GenreName"
requires_pictures = true
CONTROL = "25"

[mods.publisher.publishername]
PUBLISHER = "true"
DEVELOPER = "true"
MARKET = "50"
GENRE = "GenreName"
ONLYMOBILE = "true"
SHARE = "5"
SPEED = "3"
DATE = "JAN 1976"
COMVAL = "10000000"
"NAME EN" = "PublisherName"
NOTFORSALE = "true"
publisher_icon = "publisher_publishername_publisher_icon.png"
COUNTRY = "5"
requires_pictures = true

[mods.theme.themename]
"NAME CZ" = "ThemeName"
"NAME JA" = "ThemeName"
GENRES = "<Adventure><Building Game><Economic Simulation><Fighting Game><First-Person Shooter>"
"NAME PB" = "ThemeName"
"NAME AR" = "ThemeName"
"NAME CT" = "ThemeName"
"NAME FR" = "ThemeName"
"NAME IT" = "ThemeName"
"NAME ES" = "ThemeName"
"NAME HU" = "ThemeName"
"NAME EN" = "ThemeName"
"NAME KO" = "ThemeName"
"NAME RU" = "ThemeName"
"NAME CH" = "ThemeName"
"NAME TU" = "ThemeName"
"NAME PL" = "ThemeName"
requires_pictures = false
"NAME GE" = "ThemeName"
"NAME RO" = "ThemeName"
AGE = "0"

[mods.gameplay_feature.gameplayfeaturename]
"RES POINTS" = "500"
PRICE = "50000"
BAD = "<Building Game><Economic Simulation>"
GRAPHIC = "30"
TYP = "4"
"DESC EN" = "GameplayFeatureDescription"
DATE = "JAN 1976"
TECH = "30"
"NAME EN" = "GameplayFeatureName"
GAMEPLAY = "30"
SOUND = "30"
GOOD = "<Racing><Real-Time Strategy><Role-Playing Game>"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.npc_engine.npcenginename]
PLATFORM = "Personal Computer"
DATE = "JAN 1976"
"NAME EN" = "NpcEngineName"
PRICE = "30000"
GENRE = "Action"
SHARE = "5"
requires_pictures = false

[mods.copy_protect.copyprotectionname]
DATE = "JAN 1976"
"NAME EN" = "CopyProtectionName"
PRICE = "30000"
requires_pictures = false
"DEV COSTS" = "35000"

[mods.hardware.hardwarename]
DATE = "JAN 1976"
ONLY_HANDHELD = ""
"NAME EN" = "HardwareName"
"RES POINTS" = "500"
PRICE = "500000"
TYP = "0"
requires_pictures = true
"DEV COSTS" = "1000000"
TECHLEVEL = "1"
